version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      tanstack:
        patterns: ["@tanstack/*"]
      minor-and-patch:
        update-types: ["minor", "patch"]
  - package-ecosystem: "pip"
    directories:
        - "/e2e-cli-csv-json"
        - "/experiments/openrouter-gpt41mini"
        - "/experiments/openrouter-gpt4omini"
        - "/experiments/timeout-smoke-test"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
